version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - "$PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${your_project}:/usr/share/nginx/html"  # <---- config yours
    networks:
      - app_net
    container_name: "docker-www-nginx"
  php:
    build: ./php
    ports: ["9000"]
    # links:
    #   - mysql
    volumes:
      - "${your_project}:/var/www"  # <---- config yours
    networks:
      - app_net
    container_name: "docker-www-php"
  # mysql:  optional
  #   image: mysql:5.7
  #   ports: ["3306"]
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #   volumes:
  #     - "$PWD/mysql:/var/lib/mysql"
  #   networks:
  #     - app_net
  #   container_name: "docker-www-mysql"
networks:
  app_net:

